package org.common.dao;


import org.common.domain.DataEntity;

import java.util.List;

/**
 * Author: ICL
 * Date:2018/10/22
 * Description:
 * Created by ICL on 2018/10/22.
 */
public interface CurdDao<T extends DataEntity, ID> extends BaseDao {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_T
     *
     * Fri Oct 26 20:51:19 CST 2018
     */
    int deleteByPrimaryKey(ID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_T
     *
     *  Fri Oct 26 20:51:19 CST 2018
     */
    int insert(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_T
     *
     *  Fri Oct 26 20:51:19 CST 2018
     */
    int insertSelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_T
     *
     *  Fri Oct 26 20:51:19 CST 2018
     */
    T selectByPrimaryKey(ID id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_T
     *
     *  Fri Oct 26 20:51:19 CST 2018
     */
    int updateByPrimaryKeySelective(T record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_T
     *
     *  Fri Oct 26 20:51:19 CST 2018
     */
    int updateByPrimaryKey(T record);


    /**
     * 查询所有
     * @return
     */
    List<T> findAll();//获取所有

    /**
     * 分页查询
     * @param record
     * @return
     */
    List<T> pageInfo(T record);

    /**
     * 根据条件查询
     * @param record
     * @return
     */
    List<T> findByCondition(T record);//根据条件查找

}
